# Generated by Django 4.0.2 on 2022-02-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas_extra', '0002_registrohorasextra_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohorasextra',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
