# Generated by Django 4.0.2 on 2022-02-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas_extra', '0003_registrohorasextra_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohorasextra',
            name='utilizadas',
            field=models.BooleanField(default=False),
        ),
    ]
